document.addEventListener('DOMContentLoaded',()=>{
const input=document.getElementById('fileInput'), choose=document.getElementById('selectFileButton'), area=document.getElementById('uploadArea'), options=document.getElementById('conversionOptions'), messages=document.getElementById('uploadMessages');
const modal=document.getElementById('toolModal'), modalTitle=document.getElementById('modalTitle'), modalHint=document.getElementById('modalHint'), modalFields=document.getElementById('modalFields'), modalRun=document.getElementById('modalRun'), modalClose=document.getElementById('modalClose'), modalResult=document.getElementById('modalResult');
let uploaded=null, selectedTool=null, selectedMerge=[];
choose.onclick=()=>input.click();
input.onchange=()=>{const fs=[...input.files]; if(fs.length>1) mergeFiles(fs); else if(fs[0]) upload(fs[0]);};
['dragover','dragenter'].forEach(e=>area.addEventListener(e,x=>{x.preventDefault();area.classList.add('dragging')}));
['dragleave','drop'].forEach(e=>area.addEventListener(e,x=>{x.preventDefault();area.classList.remove('dragging')}));
area.addEventListener('drop',e=>{const fs=[...e.dataTransfer.files]; if(fs.length>1)mergeFiles(fs); else if(fs[0])upload(fs[0]);});
modalClose.onclick=()=>modal.hidden=true; modal.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true});
async function upload(file){messages.innerHTML=`<div class="status-box">Uploading <b>${esc(file.name)}</b>…</div>`;const fd=new FormData();fd.append('file',file);try{const r=await fetch('/api/upload',{method:'POST',body:fd});const d=await r.json();if(!d.success)throw Error(d.error);uploaded=d.file;messages.innerHTML=`<div class="uploaded-file-info"><span>Ready</span><b>${esc(file.name)}</b></div>`;loadOptions(d.file.filename)}catch(e){messages.innerHTML=`<div class="conversion-error">${esc(e.message)}</div>`}}
async function mergeFiles(files){if(files.some(f=>!f.name.toLowerCase().endsWith('.pdf'))){messages.innerHTML='<div class="conversion-error">Multiple selection is only used for Merge PDF and accepts PDF files.</div>';return}selectedMerge=[];messages.innerHTML='<div class="status-box">Uploading PDFs in selected order…</div>';for(const f of files){const fd=new FormData();fd.append('file',f);const r=await fetch('/api/upload',{method:'POST',body:fd});const d=await r.json();if(!d.success){messages.innerHTML=`<div class="conversion-error">${esc(d.error)}</div>`;return}selectedMerge.push(d.file)}uploaded=selectedMerge[0];messages.innerHTML=`<div class="uploaded-file-info"><span>${selectedMerge.length} PDFs ready</span><b>${esc(files.map(f=>f.name).join(', '))}</b></div>`;renderOptions([{id:'merge_pdf',name:'Merge PDF',kind:'tool'}]);}
async function loadOptions(filename){const r=await fetch('/api/conversions?filename='+encodeURIComponent(filename));const d=await r.json();if(!d.success){showError(d.error);return}renderOptions(d.conversions)}
function renderOptions(items){options.innerHTML='';if(!items.length){options.innerHTML='<div class="empty-state"><span>—</span><p>No supported action for this file.</p></div>';return}const list=document.createElement('div');list.className='conversion-list';items.forEach(item=>{const b=document.createElement('button');b.className='conversion-option'+(item.kind==='tool'?' tool':'');b.innerHTML=`<span>${esc(item.name)}</span><span>→</span>`;b.onclick=()=>runItem(item,b);list.appendChild(b)});options.appendChild(list)}
async function runItem(item,button){if(item.kind==='editor'){const url=(item.id==='edit_pdf'?'/pdf-editor?filename=':'/word-editor?filename=')+encodeURIComponent(uploaded.filename);location.href=url;return}if(item.id==='merge_pdf'){if(selectedMerge.length>=2)return executeMerge(selectedMerge,button);return chooseMorePdfs(button)}if(item.kind==='tool')return openTool(item);button.disabled=true;button.textContent='Working…';try{const r=await fetch('/api/convert',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:uploaded.filename,conversion_id:item.id})});const d=await r.json();if(!d.success)throw Error(d.error);showResult(d,item.name)}catch(e){showError(e.message)}finally{button.disabled=false;button.innerHTML=`<span>${esc(item.name)}</span><span>→</span>`}}
function chooseMorePdfs(button){const p=document.createElement('input');p.type='file';p.accept='.pdf';p.multiple=true;p.onchange=async()=>{const fs=[...p.files];if(!fs.length)return;selectedMerge=[uploaded];for(const f of fs){const fd=new FormData();fd.append('file',f);const r=await fetch('/api/upload',{method:'POST',body:fd});const d=await r.json();if(!d.success){showError(d.error);return}selectedMerge.push(d.file)}executeMerge(selectedMerge,button)};p.click()}
async function executeMerge(files,button){button.disabled=true;button.textContent='Merging…';try{const r=await fetch('/api/merge-pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filenames:files.map(f=>f.filename)})});const d=await r.json();if(!d.success)throw Error(d.error);showResult(d,'Merge PDF')}catch(e){showError(e.message)}finally{button.disabled=false;button.innerHTML='<span>Merge PDF</span><span>→</span>'}}
function openTool(item){selectedTool=item;modal.hidden=false;modalTitle.textContent=item.name;modalResult.innerHTML='';const id=item.id;let fields='';let hint='';if(id==='split_pdf'){hint='Split the document into individual files or use a page range.';fields=`<div class="modal-field"><label>Pages per file</label><input id="toolValue" type="number" min="1" value="1"></div><div class="modal-field"><label>Optional page range (leave blank for all)</label><input id="toolPages" placeholder="1-3,5"></div>`}else if(id==='rotate_pdf'){hint='Rotate all pages or enter selected pages.';fields=`<div class="modal-field"><label>Degrees</label><select id="toolDegrees"><option>90</option><option>180</option><option>270</option></select></div><div class="modal-field"><label>Pages (blank = all)</label><input id="toolPages" placeholder="1,3,4"></div>`}else if(['delete_pages','extract_pages'].includes(id)){hint='Use page numbers or ranges such as 2,4-6.';fields=`<div class="modal-field"><label>Pages</label><input id="toolPages" placeholder="2,4-6"></div>`}else if(id==='reorder_pages'){hint='Enter every page exactly once in the new order.';fields=`<div class="modal-field"><label>New order</label><input id="toolPages" placeholder="3,1,2,4"></div>`}else if(id==='page_numbers'){hint='Add page numbers to every page.';fields=`<div class="modal-field"><label>Position</label><select id="toolPosition"><option value="bottom-right">Bottom right</option><option value="bottom-left">Bottom left</option><option value="top-right">Top right</option><option value="top-left">Top left</option></select></div><div class="modal-field"><label>Starting number</label><input id="toolStart" type="number" value="1"></div>`}else if(id==='watermark_pdf'){hint='Overlay a subtle watermark across every page.';fields=`<div class="modal-field"><label>Watermark text</label><input id="toolText" value="CONFIDENTIAL"></div>`}else if(id==='compress_pdf'){hint='Optimise streams, objects, images and fonts.';fields=`<div class="modal-field"><label>Mode</label><select id="toolMode"><option>Balanced</option><option>Maximum</option></select></div>`}else if(id==='extract_images'){hint='Extract embedded images and return a ZIP file.'}else if(id==='edit_pdf'){location.href='/pdf-editor?filename='+encodeURIComponent(uploaded.filename);return}modalHint.textContent=hint;modalFields.innerHTML=fields;modalRun.onclick=()=>executeTool(id)}
async function executeTool(id){modalRun.disabled=true;modalRun.textContent='Processing…';try{let payload={filename:uploaded.filename,operation:id.replace('_pdf','')};if(id==='split_pdf'){const p=document.getElementById('toolPages')?.value;const per=document.getElementById('toolValue')?.value;const r=await fetch('/api/pdf-operation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:uploaded.filename,operation:'split',pages_per_file:+per||1,page_spec:p||''})});const d=await r.json();if(!d.success)throw Error(d.error);showResult(d,'Split PDF');modal.hidden=true;return}if(id==='compress_pdf'){const r=await fetch('/api/convert',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:uploaded.filename,conversion_id:'compress_pdf'})});const d=await r.json();if(!d.success)throw Error(d.error);showResult(d,'Compress PDF');modal.hidden=true;return}if(id==='extract_images'){payload.operation='extract_images'}else if(id==='rotate_pdf'){payload.operation='rotate';payload.degrees=+document.getElementById('toolDegrees').value;payload.pages=parsePages(document.getElementById('toolPages').value)}else if(id==='delete_pages'){payload.operation='delete_pages';payload.pages=parsePages(document.getElementById('toolPages').value)}else if(id==='extract_pages'){payload.operation='extract_pages';payload.pages=parsePages(document.getElementById('toolPages').value)}else if(id==='reorder_pages'){payload.operation='reorder_pages';payload.order=parsePages(document.getElementById('toolPages').value)}else if(id==='page_numbers'){payload.operation='page_numbers';payload.position=document.getElementById('toolPosition').value;payload.start=+document.getElementById('toolStart').value}else if(id==='watermark_pdf'){payload.operation='watermark';payload.text=document.getElementById('toolText').value}else throw Error('Tool is not configured.');const r=await fetch('/api/pdf-operation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!d.success)throw Error(d.error);showResult(d,selectedTool.name);modal.hidden=true}catch(e){modalResult.innerHTML=`<div class="conversion-error">${esc(e.message)}</div>`}finally{modalRun.disabled=false;modalRun.textContent='Run tool →'}}
function parsePages(s){return String(s||'').split(',').flatMap(x=>{x=x.trim();if(!x)return[];if(x.includes('-')){let[a,b]=x.split('-').map(Number);let out=[];for(let i=Math.min(a,b);i<=Math.max(a,b);i++)out.push(i);return out}return [Number(x)]}).filter(Boolean)}
function showResult(d,name){const f=d.file;if(!f&&d.files){options.insertAdjacentHTML('afterend',`<div class="conversion-result"><strong>${esc(name)} completed</strong>${d.files.map(x=>`<a class="btn btn-soft" href="${x.download_url}" download>Download ${esc(x.filename)}</a>`).join('')}</div>`);return}if(!f)return;options.insertAdjacentHTML('afterend',`<div class="conversion-result"><strong>${esc(name)} completed</strong><span>${esc(f.filename)}</span><a class="btn btn-primary" href="${f.download_url}" download>Download result ↓</a></div>`)}
function showError(m){options.insertAdjacentHTML('afterend',`<div class="conversion-error">${esc(m)}</div>`)}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
});
